## 1-1 : Affine Functions with 1 Featrue

### Code.1-1-1 : Affine Function

In [1]:
#!pip install tensorflow-gpu
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) # Input setting(Note : input -> matrix)
dense = Dense(units=1, activation = 'linear') # imp. an affine function

print(x)
print(x.shape)

y_tf = dense(x) # w, b // z = xw+b // forward propagation + params initialization

print(y_tf)

W, B = dense.get_weights()
print(W, B)
y_man = tf.linalg.matmul(x,W) + B  # forward propagation(manual)

# print results
print('===== Input/Weight/Bias =====')
print(f'x : {x.shape} / {x.numpy()}')
print(f'W : {y_tf.shape} / {W}')
print(f'B : {B.shape} / {B}')

print('===== Ouputs =====')
print(f"y(Tensorflow) : {y_tf.shape} / {y_tf.numpy()}")
print(f"y(Manual) : {y_man.shape} / {y_man.numpy()}")

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
(1, 1)
tf.Tensor([[-2.0495725]], shape=(1, 1), dtype=float32)
[[-0.20495725]] [0.]
===== Input/Weight/Bias =====
x : (1, 1) / [[10.]]
W : (1, 1) / [[-0.20495725]]
B : (1,) / [0.]
===== Ouputs =====
y(Tensorflow) : (1, 1) / [[-2.0495725]]
y(Manual) : (1, 1) / [[-2.0495725]]


### Code.1-1-1 : Params Initialization

In [2]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

# weight/bias setting
w,b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

print(w_init, b_init)

# imp. an affine function
dense = Dense(units=1, activation = 'linear',
              kernel_initializer = w_init,
              bias_initializer = b_init)

y_tf = dense(x)
W, B = dense.get_weights()
print(y_tf)

# print results
print(f'W : {W.shape} / {W}')
print(f'B : {B.shape} / {B}')

<tensorflow.python.keras.initializers.initializers_v2.Constant object at 0x0000012ABCF82EC8> <tensorflow.python.keras.initializers.initializers_v2.Constant object at 0x0000012ABCF82FC8>
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W : (1, 1) / [[10.]]
B : (1,) / [20.]


## 1-2 : Affine Functions with n Features

### Code.1-2-1 : Affine Functions with n Featrues

In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape = (1,10), minval=0, maxval=10)
print(x.shape, '\n', x)

dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

# print results
print('===== Input/Weight/Bias =====')
print(f'x : {x.shape} / {x.numpy()}')
print(f'W : {W.shape} / {W}')
print(f'B : {B.shape} / {B}')

print('===== Ouputs =====')
print(f"y(Tensorflow) : {y_tf.shape} / {y_tf.numpy()}")
print(f"y(Manual) : {y_man.shape} / {y_man.numpy()}")

(1, 10) 
 tf.Tensor(
[[5.5458355 1.9355118 6.746477  6.4523163 5.092597  1.2913358 4.933592
  4.6577883 7.342676  9.051614 ]], shape=(1, 10), dtype=float32)
===== Input/Weight/Bias =====
x : (1, 10) / [[5.5458355 1.9355118 6.746477  6.4523163 5.092597  1.2913358 4.933592
  4.6577883 7.342676  9.051614 ]]
W : (10, 1) / [[-0.47694248]
 [-0.6814187 ]
 [-0.20151943]
 [ 0.66904074]
 [-0.3782255 ]
 [ 0.23593342]
 [-0.45601368]
 [-0.19695729]
 [ 0.25848818]
 [ 0.6749005 ]]
B : (1,) / [0.]
===== Ouputs =====
y(Tensorflow) : (1, 1) / [[2.2116594]]
y(Manual) : (1, 1) / [[2.2116594]]


## 1-3: Activation Layers

### Code. 1-3-1: Activation Layers

In [6]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1,5)) # input setting

# imp. activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward prpagation(Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward prpagation(mannual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print(f'x : {x.shape}, {x.numpy()}')

print(f'Sigmoid(Tensorflow) : {y_sigmoid_tf.shape}, {y_sigmoid_tf.numpy()}')
print(f'Sigmoid(manual) : {y_sigmoid_man.shape}, {y_sigmoid_man.numpy()}')
print('\n')
print(f'Tanh(Tensorflow) : {y_tanh_tf.shape}, {y_tanh_tf.numpy()}')
print(f'Tanh(manual) : {y_tanh_man.shape}, {y_tanh_man.numpy()}')
print('\n')
print(f'ReLU(Tensorflow) : {y_relu_tf.shape}, {y_relu_tf.numpy()}')
print(f'ReLU(manual) : {y_relu_man.shape}, {y_relu_man.numpy()}')

x : (1, 5), [[-0.39082974  0.10974757 -1.7390275  -0.94429874  0.66350085]]
Sigmoid(Tensorflow) : (1, 5), [[0.40351757 0.52740943 0.14943649 0.28003284 0.66004634]]
Sigmoid(manual) : (1, 5), [[0.40351757 0.52740943 0.14943649 0.28003284 0.6600464 ]]


Tanh(Tensorflow) : (1, 5), [[-0.37207532  0.10930905 -0.9401138  -0.73719114  0.58068854]]
Tanh(manual) : (1, 5), [[-0.37207532  0.10930903 -0.9401138  -0.7371911   0.58068854]]


ReLU(Tensorflow) : (1, 5), [[0.         0.10974757 0.         0.         0.66350085]]
ReLU(manual) : (1, 5), [[0.         0.10974757 0.         0.         0.66350085]]


### Code. 1-3-2 : Activation in Dense Layer

In [8]:
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1, 5))  # input setting

# imp. artifical neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print(f'AN with Sigmoid : {y_sigmoid.shape}, {y_sigmoid.numpy()}')
print(f'AN with Tanh : {y_tanh.shape}, {y_tanh.numpy()}')
print(f'AN with Relu : {y_relu.shape}, {y_relu.numpy()}')

print("\n ======== \n")

# forward propagation(manual)
W, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + b
a = 1 / (1+exp(-z))

print(f"Activation value(Tensorflow) : {y_sigmoid.shape}, {y_sigmoid.numpy()}")
print(f"Activation value(manual) : {a.shape}, {a.numpy()}")

AN with Sigmoid : (1, 1), [[0.31697944]]
AN with Tanh : (1, 1), [[0.9979504]]
AN with Relu : (1, 1), [[0.]]


Activation value(Tensorflow) : (1, 1), [[0.31697944]]
Activation value(manual) : (1, 1), [[0.31697944]]


## 1-4 : Artifical Neurons

### Code.1-4-1 : Artificial Neurons

In [10]:
"""
검증
tensorflow에서 기본적으로 제공되는 Dense layer 실제로 어떻게 동작하고 작동하는지 검증
y = ax + b의 과정을 검증
"""

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# activation = 'sigmoid'
activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape=(1, 10)) # input setting

dense = Dense(units=1, activation=activation) # imp. an affine + activation

y_tf = dense(x)
W, b = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + b
if activation == 'sigmoid':
    y_man = 1 / (1 + exp(-y_man))
elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
    y_man = maximum(x, 0)

print(f'Activation : {activation}')
print(f'y_tf : {y_tf.shape}, {y_tf.numpy()}')
print(f'y_man : {y_man.shape}, {y_man.numpy()}')

Activation : tanh
y_tf : (1, 1), [[0.5059361]]
y_man : (1, 1), [[0.5059361]]


## 1-5 : Minibatches

### Code.1-5-1 : Shapes of Dense Layers

In [11]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_features)) # generate minibatch

dense = Dense(units=1, activation='relu') # imp. an AN
y = dense(x) # forward propagation

W, b = dense.get_weights() # get weight / bias

# print results
print(f"Shape of x : {x.shape}")
print(f"Shape of W : {W.shape}")
print(f"Shape of B : {b.shape}")


Shape of x : (8, 10)
Shape of W : (10, 1)
Shape of B : (1,)


### Code.1-5-2 : Ouput Calculations

In [13]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_features)) # generate minibatch

dense = Dense(units=1, activation='sigmoid') # imp. an AN
y_tf = dense(x) # forward propagation(tensorflow)

W, b = dense.get_weights() # get weight / bias

y_man = tf.linalg.matmul(x, W) + b # forward propagation(Manual)
y_man = 1 / (1 + tf.math.exp(-y_man))

# print results
print(f"Output(tensorflow) : {y_tf.numpy()}")
print(f"Outpu(Manual : {y_man.numpy()}")
print(tf.math.equal(y_tf, y_man))

Output(tensorflow) : [[0.7586473 ]
 [0.08524176]
 [0.26782224]
 [0.57971865]
 [0.4382735 ]
 [0.27700454]
 [0.52964973]
 [0.85626656]]
Outpu(Manual : [[0.7586473 ]
 [0.08524176]
 [0.26782224]
 [0.57971865]
 [0.4382735 ]
 [0.27700454]
 [0.52964973]
 [0.85626656]]
tf.Tensor(
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]], shape=(8, 1), dtype=bool)


# Forward Propagation of Neural Networks

## Lecture.2 Dense Layers